### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by azasypkin** [azasypkin/recognizer#1]
- [x] Add node image proxy (to overcome CORS);
- [ ] Add support for Tesseract.js;
- [ ] Add support for other cloud APIs (CloudSight?).
